/*
 * Copyright 2016 ITEA 12004 SEAS Project.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.thesmartenergy.ontop.plugins;

import com.github.thesmartenergy.ontop.OntopException;
import java.util.HashMap;
import java.util.Map;

/**
 * A representations map is serialized into turtle, or generated from a turtle
 * document. It is generated by the plugin, then parsed by the dependency to be
 * used by jersey filters and resources.
 *
 * @author Maxime Lefrançois <maxime.lefrancois at emse.fr>
 */
public class GraphsMap {

    /**
     * key and value are resource paths. values must be keys for GRAPH_RESOURCES
     */
    private final Map<String, String> REDIRECTIONS = new HashMap<>();

    /**
     * key is an graph name
     */
    private final Map<String, GraphResource> GRAPH_RESOURCES = new HashMap<>();

    public void registerGraph(GraphResource graph) throws OntopException {
        registerMainUri(graph);
        registerResources(graph);
    }

    private void registerMainUri(GraphResource graph) throws OntopException {
        String graphPath = graph.getGraphPath();
        GraphResource other = GRAPH_RESOURCES.get(graphPath);
        if (other == null) {
            GRAPH_RESOURCES.put(consolidate(graphPath), graph);
        }
    }

    private void registerResources(GraphResource graph) {
        for (String resource : graph.getDefinedResources()) {
            String primaryResource = getPrimaryResourceUri(resource);
            if (!REDIRECTIONS.containsKey(primaryResource)) {
                REDIRECTIONS.put(primaryResource, graph.getGraphPath());
            }
        }
    }

    public Map<String, String> getRedirections() {
        return REDIRECTIONS;
    }


    public Map<String, GraphResource> getGraphResources() {
        return GRAPH_RESOURCES;
    }

    private String getPrimaryResourceUri(String resourceUri) {
        int pos = resourceUri.indexOf("#");
        if (pos != -1) {
            return resourceUri.substring(0, pos);
        } else {
            return resourceUri;
        }
    }

    private String consolidate(String path) {
        if (path.equals("") || path.endsWith("/")) {
            return path + "index";
        }
        return path;
    }

}